### ISSUE TITLE
It's not possible to use any command. Help pls

### ISSUE THREAD

**Issue by Terisback** [subsoap/defsteam#3]
Did everything that is stated in the article
https://www.defold.com/community/projects/86864/
Overlay appears, and Steam sees everything correctly
BUT after initialization I can't use any function
![default](https://user-images.githubusercontent.com/26527529/43691313-1a339e7a-9934-11e8-8e14-e0b87ee38613.png)
I hope for help

**Comment by subsoap** [comment]
It says Steamworks couldn't start. If you do have Steam running then you have something configured incorrectly.  Or you're not waiting until Steamworks is actually ready.

Try to run the included example with everything setup properly. E-mail me and I'll send you something to test brian@subsoap.com

**Comment by Terisback** [comment]
I set an example.
But nothing has changed
![default](https://user-images.githubusercontent.com/26527529/43746226-63a147c4-99fc-11e8-8285-7f8e20887011.png)
![default](https://user-images.githubusercontent.com/26527529/43746234-6dfb25e6-99fc-11e8-8be0-416f7907a155.png)
![default](https://user-images.githubusercontent.com/26527529/43746243-7565fe64-99fc-11e8-8d4b-75aaa04ce429.png)
![default](https://user-images.githubusercontent.com/26527529/43746248-7bbe214c-99fc-11e8-92a6-94346665ef70.png)
![default](https://user-images.githubusercontent.com/26527529/43746275-a7415c9e-99fc-11e8-9690-e24ca3d452c4.png)

**Comment by subsoap** [comment]
Problem was proper dll steam_api.dll was not in root of project.
